# Generated by Django 3.1.7 on 2021-03-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggesstions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NILL', max_length=30)),
                ('email', models.EmailField(default='NILL', max_length=100)),
                ('address', models.CharField(default='NILL', max_length=250)),
                ('mob', models.CharField(default='none', max_length=20)),
                ('suggestion', models.CharField(default='', max_length=2050)),
            ],
        ),
    ]
