# Generated by Django 3.1.7 on 2021-03-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0002_auto_20210314_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggesstions',
            old_name='id',
            new_name='msg_id',
        ),
    ]
