# Generated by Django 3.1.7 on 2021-03-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0004_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='type',
            field=models.CharField(default='NILL', max_length=40),
        ),
    ]
