# Generated by Django 3.1.7 on 2021-04-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0006_templates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggesstions',
        ),
    ]
