# Generated by Django 3.1.7 on 2021-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0010_auto_20210407_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('des', models.TextField()),
            ],
        ),
    ]
