# Generated by Django 3.1.7 on 2021-04-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0011_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
