# Generated by Django 3.1.7 on 2021-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0005_resumes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('templateFile', models.FileField(upload_to='templates')),
                ('image', models.ImageField(upload_to='tempImage')),
            ],
        ),
    ]
