# Generated by Django 3.1.7 on 2021-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0007_delete_suggesstions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggesstions',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NILL', max_length=30)),
                ('email', models.EmailField(default='NILL', max_length=100)),
                ('address', models.CharField(default='NILL', max_length=250)),
                ('mob', models.CharField(default='none', max_length=20)),
                ('suggestion', models.CharField(default='', max_length=2050)),
            ],
        ),
    ]
