# Generated by Django 3.1.7 on 2021-04-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NowOwnResume', '0008_suggesstions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='image',
            field=models.ImageField(upload_to='media/tempImage'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='templateFile',
            field=models.FileField(upload_to='media/templates'),
        ),
    ]
